
steps:
  - name: "DateFeatures"
    class: "src.features.dates.DatePartTransformer"
    params:
      parts: ["year", "month", "day", "dayofweek", "is_weekend", "is_wage_day"]
      column: "date"

  - name: "LagFeatures"
    class: "src.features.lags.LagTransformer"
    params:
      column: "sales"
      lags: [1, 7, 14, 28]
      groupby: ["store_nbr", "family"]
  
  - name: "RollingFeatures"
    class: "src.features.rolling.RollingWindowTransformer"
    params:
      columns: ["sales"]
      groupby: ["store_nbr", "family"]
      window: 7
      stats: ["mean", "std"]
