[project]
name = "kaggle-store-sales-ts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "kaggle>=1.8.4",
    "lightgbm>=4.6.0",
    "matplotlib",
    "nbformat>=5.10.4",
    "numpy",
    "pandas",
    "pytest",
    "pyyaml>=6.0.3",
    "scikit-learn",
    "seaborn",
]
